### ISSUE TITLE
Not working on Node 4.2.2

### ISSUE THREAD

**Issue by terehov** [freefoote/node-red-flows-mongo#1]
Hi!

I love your idea of saving node-RED data into Mongo, however I cannot get it to work. 
Do you have any Idea what this error could mean? 

Thanks a lot! 
---------------------------------------
Potentially unhandled rejection [2] TypeError: Cannot read property 'missingTypes' of null
    at start (/Users/nodered/node_modules/node-red/red/nodes/flows/index.js:202:25)
    at tryCatchReject (/Users/nodered/node_modules/node-red-flows-mongo/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/nodered/node_modules/node-red-flows-mongo/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/nodered/node_modules/node-red-flows-mongo/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/Users/nodered/node_modules/node-red-flows-mongo/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/nodered/node_modules/node-red-flows-mongo/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/nodered/node_modules/node-red-flows-mongo/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
    at process.<anonymous> (/Users/nodered/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)
TypeError: config.forEach is not a function
    at Object.module.exports.parseConfig (/Users/nodered/node_modules/node-red/red/nodes/flows/util.js:52:16)
    at setConfig (/Users/nodered/node_modules/node-red/red/nodes/flows/index.js:88:34)
    at /Users/nodered/node_modules/node-red/red/nodes/flows/index.js:71:20
    at tryCatchReject (/Users/nodered/node_modules/node-red-flows-mongo/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/nodered/node_modules/node-red-flows-mongo/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/nodered/node_modules/node-red-flows-mongo/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/Users/nodered/node_modules/node-red-flows-mongo/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/nodered/node_modules/node-red-flows-mongo/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/nodered/node_modules/node-red-flows-mongo/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
    at process.<anonymous> (/Users/nodered/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)

**Comment by freefoote** [comment]
Hello,

I'm using it with Node 0.12 at the moment. When I have some time in a few weeks I'll try it with Node 4.2.2.

Sorry!
